### ISSUE TITLE
Error following build instructions

### ISSUE THREAD

**Issue by SteveSanderson** [lrz/mono-wasm#1]
First, this looks amazing, and I'm looking forwards to being able to have a go with it!

I tried to follow the build instructions in README.md. First I tried on Ubuntu but hit various issues which are probably to do with needing different flags to indicate the build platform. Then, since it looks like the instructions are designed for macOS, I tried it on a Mac, and all went well until trying to build the Mono compiler.

After running these lines:

```
$ ./autogen.sh --host=i386-darwin --with-cross-offsets=offsets-wasm32.h CFLAGS="-DCOMPILE_WASM32 -DMONO_CROSS_COMPILE" CXXFLAGS="-DCOMPILE_WASM32 -DMONO_CROSS_COMPILE" --disable-boehm --with-sigaltstack=no --enable-llvm --enable-llvm-runtime --with-llvm=../llvm-mono-build --disable-btls --with-runtime_preset=testing_aot_full
$ make
```

... I'm getting this error (after a lot of other build output):

```
...
cd /Users/myusername/Desktop/mono-wasm/mono-compiler/mcs && /Applications/Xcode.app/Contents/Developer/usr/bin/make --no-print-directory -s NO_DIR_CHECK=1 PROFILES='binary_reference_assemblies net_4_x xbuild_12 xbuild_14         ' CC='gcc' all-profiles

Unhandled Exception:
System.MissingMethodException: Method 'AppContext.get_BaseDirectory' not found.
  at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.MainCore (System.String[] args) <0x10f271ff0 + 0x000b3> in <filename unknown>:0 
  at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main (System.String[] args) <0x10f271da0 + 0x00023> in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: Method 'AppContext.get_BaseDirectory' not found.
  at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.MainCore (System.String[] args) <0x10f271ff0 + 0x000b3> in <filename unknown>:0 
  at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main (System.String[] args) <0x10f271da0 + 0x00023> in <filename unknown>:0 
make[6]: *** [build/deps/basic-profile-check.exe] Error 1
*** The runtime 'mono' doesn't appear to be usable.
*** Trying the 'monolite-darwin/1050500002' directory.
This mono runtime is compiled for cross-compiling. Only the --aot option is supported.
make[8]: *** [build/deps/basic-profile-check.exe] Error 1
*** The contents of your 'monolite-darwin/1050500002' directory may be out-of-date
*** You may want to try 'make get-monolite-latest'
make[8]: *** [do-profile-check-monolite] Error 1
make[7]: *** [do-profile-check] Error 2
make[6]: *** [do-profile-check-monolite] Error 2
make[5]: *** [do-profile-check] Error 2
make[4]: *** [profile-do--basic--all] Error 2
make[3]: *** [profiles-do--all] Error 2
make[2]: *** [all-local] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

Was this not something that happened when you ran it? Do you know of any workaround for this?

PS there were also a load of warnings further up, such as the following, though I don't know if this is normal or expected:

```
In file included from ../../mono/utils/mono-threads.h:14:
../../mono/utils/mono-os-semaphore.h:114:20: warning: comparison of integers of different signs: 'clock_res_t'
      (aka 'int') and 'unsigned long long' [-Wsign-compare]
        while (ts.tv_nsec >= NSEC_PER_SEC) {
```

**Comment by lrz** [comment]
Hi Steve!

Thanks for giving this a try! Now that you mention it I don't think the Mono compiler build is supposed to succeed (to be fair I personally use local "make" commands inside it). All you really need is the `mono` executable and the `mscorlib.dll` library. If the build crashes later on it's not a big deal (for the demo at least).

It also requires a Mac as you found out (I should definitely mention that in the README file).

Since we are talking I would like to try to get your Blazor project running with the compiler, I am supposing that this is what you're trying to do as well, I would love to chat if you want!

**Comment by SteveSanderson** [comment]
Aha, thanks for the info. The `mono` executable was already produced before the error. So I tried to continue following the instructions, but unfortunately running `make` in the `build` directory produces this:

```
/usr/bin/clang -I../binaryen/src -Wno-sign-compare -std=c++1y -UNDEBUG -fexceptions -DNO_EMSCRIPTEN_GLUE -c ../binaryen/src/wasm-linker.cpp -o wasm-linker.o
/usr/bin/clang -c jsmin.c -o jsmin.o
/usr/bin/clang++ -I/Users/username/Desktop/mono-wasm/llvm/include -I/Users/username/Desktop/mono-wasm/llvm-build/include  -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -O3 -DNDEBUG  -fno-exceptions -fno-rtti -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -L/Users/username/Desktop/mono-wasm/llvm-build/lib -Wl,-search_paths_first -Wl,-headerpad_max_install_names -Wno-gnu -Wno-sign-compare -std=c++1y -UNDEBUG -fexceptions -I../binaryen/src -g mono-wasm.cpp -o mono-wasm -lncurses -lz  ../binaryen/lib/libwasm.a  ../binaryen/lib/libsupport.a  ../binaryen/lib/libpasses.a  ../binaryen/lib/libast.a  ../binaryen/lib/libcfg.a  ../binaryen/lib/libasmjs.a jsmin.o wasm-linker.o -lLLVMWebAssemblyDisassembler -lLLVMMCDisassembler -lLLVMWebAssemblyCodeGen -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMDebugInfoCodeView -lLLVMDebugInfoMSF -lLLVMCodeGen -lLLVMTarget -lLLVMWebAssemblyDesc -lLLVMWebAssemblyInfo -lLLVMWebAssemblyAsmPrinter -lLLVMipo -lLLVMInstrumentation -lLLVMVectorize -lLLVMScalarOpts -lLLVMInstCombine -lLLVMLinker -lLLVMTransformUtils -lLLVMIRReader -lLLVMAsmParser -lLLVMBitWriter -lLLVMAnalysis -lLLVMProfileData -lLLVMObject -lLLVMMCParser -lLLVMMC -lLLVMBitReader -lLLVMCore -lLLVMBinaryFormat -lLLVMSupport -lLLVMDemangle
mono-wasm.cpp:355:30: error: no member named 'Default' in namespace 'llvm::CodeModel'
            llvm::CodeModel::Default, opt_level);
            ~~~~~~~~~~~~~~~~~^
1 error generated.
make: *** [mono-wasm] Error 1
```

If you have any recollection of how you got past this issue (or why you didn't hit it), please let me know!

Yes, I am hoping to get Blazor running on Mono on WebAssembly. That would really move things along - I think a lot of people would find that compelling. If you'd be interested in working with me on that goal let's chat.

One key low-level requirement from the runtime would be .NET-JS interop, i.e., allowing function calls in both directions. When I did this on DNA, I only implemented support for invoking functions that take a string and return a string - that was sufficient, as everything else could be encoded as JSON. Plus the .NET runtime needs to support GCHandle and GC pinning so that .NET object references could be round-tripped between both sides. I think everything else could be built on those primitives. What sort of .NET-JS interop is possible in the Mono prototype you have at the moment?

**Comment by lrz** [comment]
In my environment this enumeration is defined in the `llvm/Support/CodeGen.h` file, can you check if it's in one of the header paths that are passed to the compiler invocation? Normally that file should be within your `/Users/username/Desktop/mono-wasm/llvm/include` directory, unless I messed up the build instructions!

I would love to work with you on this, is there an email address I can reach you about this? Feel free to ping me too: laurent.sansonetti@microsoft.com

**Comment by SteveSanderson** [comment]
Ah, I see, thanks. In the version of LLVM I got, the enum entries are different. Mine looks like this: http://llvm.org/doxygen/namespacellvm_1_1CodeModel.html - there's no `Default` entry. So I changed `llvm::CodeModel::Default` to `llvm::CodeModel::Medium` and the build got one step further.

It now fails shortly after saying

```
Undefined symbols for architecture x86_64:
  "wasm::emscripten::makeDynCallThunks(wasm::Module&, std::__1::vector<wasm::Name, std::__1::allocator<wasm::Name> > const&)", referenced from:
      wasm::Linker::emscriptenGlue(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) in wasm-linker.o
  "wasm::emscripten::generateEmscriptenMetadata(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, wasm::Module&, std::__1::unordered_map<wasm::Address, wasm::Address, std::__1::hash<wasm::Address>, std::__1::equal_to<wasm::Address>, std::__1::allocator<std::__1::pair<wasm::Address const, wasm::Address> > >, wasm::Address, std::__1::vector<wasm::Name, std::__1::allocator<wasm::Name> > const&)", referenced from:
      wasm::Linker::emscriptenGlue(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) in wasm-linker.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [mono-wasm] Error 1
```

I suppose the issue is that it should be doing a 32-bit build but for some reason is trying to do a 64-bit build. But at this point I don't know whether the build instructions are wrong or whether I've followed them wrong, since I've entered and exited the process a bunch of different times :) Do you happen to know if the build target should be determined by something transient like an environment variable, or whether it's purely a function of files on disk? Because I've opened and closed my terminal and would have lost any env vars that should have been set earlier in the script. Not keen on restarting from the beginning as the LLVM builds take hours (literally).

Anyway I'll email you to follow up about getting Blazor running. Didn't know you worked at Microsoft too!

**Comment by lrz** [comment]
Oh I see now, LLVM changed this in the meantime, that makes sense, I will have to update the code later on.

About the linker issue, can you apply the following patch in the `../binaryen` directory? I also forgot to push it (very sorry about all these issues!).

https://gist.github.com/lrz/5a27a1466551a153ec944b6f26d01187

Looking forward to chat with you!

**Comment by lrz** [comment]
Closing as this may been fixed now.
