### ISSUE TITLE
Bad scammer to my Ubuntu 18.04!!!!

### ISSUE THREAD

**Issue by ghost** [lrz/mono-wasm#19]
Why do you hurt my Ubuntu 18.04?

I have tried but I give up Mono-Wasm than it happens error because your llvm installation saves in /usr/local

I am mad now because I want use only /usr not /usr/local. I have removed /usr/local

and  can't remove saved paths from include and library
See https://github.com/mono/mono/issues/10583

PLEASE REMOVE UNUSABLE PATH from INCULDUE and LIBRARY

**Comment by stefan-schweiger** [comment]
@sourceskyboxer as stated a hundred times already this repository is abandoned and not in active development anymore. If you want to use mono with webassembly look into offical mono repository.

Extended instructions can be found [here](https://github.com/mono/mono/tree/master/sdks/wasm) in the README.

@lrz @migueldeicaza can't you just close the repository and add a disclaimer?

**Comment by ghost** [comment]
What do you mean? I already tried like you said 
https://github.com/migueldeicaza/mono-wasm/issues/19#issuecomment-421005461 I have tried - No success because make throws error because I don't want install Android How do I ignore Android build?

I should close?

But how do I uninstall from /usr/local?????? But I hate if include-path are died I want remove PLEASE HELP ME!

I HAVE TOLD YOU: I HAVE PROBLEM:
```
emcc -g4 -Os -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s BINARYEN=1 -s "BINARYEN_TRAP_MODE='clamp'" -s TOTAL_MEMORY=134217728 -s ALIASING_FUNCTION_POINTERS=0 -s ASSERTIONS=2 --js-library library_mono.js driver.o $(TOP)/sdks/out/wasm-interp/lib/libmonosgen-2.0.a -o debug/mono.js -s NO_EXIT_RUNTIME=1 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall', 'FS_createPath', 'FS_createDataFile', 'cwrap', 'setValue', 'getValue', 'UTF8ToString']"
TOP: command not found
WARNING  root: LLVM version appears incorrect (seeing "(tags/RELEASE_600/final)", expected "3.4")
INFO     root: (Emscripten: Running sanity checks)
ERROR    root: driver.o: No such file or directory ("driver.o" was expected to be an input file, based on the commandline arguments provided)
```
But I don't know because mono-wasm made by @lrz it looks like promising... But failure for my Ubuntu 18.04 But I can't remove from sudo make uninstall with stupid directory /usr/local

PS: I found sudo make -n install but it can't remove complete from /usr/local
