### ISSUE TITLE
Makefile appears to be outdated

### ISSUE THREAD

**Issue by dustinsoftware** [lrz/mono-wasm#6]
I ran into a few issues when trying to run the [make](https://github.com/lrz/mono-wasm/blob/master/Makefile) step at the very end of the directions. Not sure if I followed the directions incorrectly or if something else is wrong.

1. ~~According to the `README`, the makefile should be in the `build` directory. However, there is none, and trying to build with the makefile in the root crashes because the relative paths are incorrect.~~ I missed the step where this repo was checked out to the `build` directory at the very beginning.
1. After correcting the paths, I get the error `make: *** No rule to make target 'wasm-linker.o', needed by 'mono-wasm'.  Stop.`. I can't find `wasm-linker` anywhere, what is step is supposed to produce that file?

**Comment by lrz** [comment]
Oops sorry about that, I forgot to remove the `wasm-linker.o` dependency at the same time I removed the binaryen dependency. It has been fixed as of c46c1e0185d1cabd4a19798e9f55673f767369da.
