### ISSUE TITLE
Can't resolve lib

### ISSUE THREAD

**Issue by ahmad2smile** [lrz/mono-wasm#9]
I tried compiling exe file with latest release but couldn't get anywhere.

`$ mono-wasm -i Program.exe -o output`
`can't resolve 'lib' directory`

**Comment by lrz** [comment]
At the moment you have to use `mono-wasm` from its relative installation path. Ex. `../some-directory/mono-wasm -i Program.exe -o output`.

**Comment by ahmad2smile** [comment]
I had added the path to $PATH and just thought its the same thing. Sorry for my ignorance. Thanks alot man it worked.
